export enum UserPermission {
    FULL_CUSTOMER = 100,
    VIEW_CUSTOMER,
    ADD_CUSTOMER,
    DELETE_CUSTOMER,
    EDIT_CUSTOMER,

    VIEW_RESULT = 111,
    DOWNLOAD_RESULT,

    FULL_FEEDBACK = 120,
    VIEW_FEEDBACK,
    EDIT_FEEDBACK,
    DELETE_FEEDBACK,
    ADD_FEEDBACK,

    FULL_POLL = 130,
    VIEW_POLL,
    EDIT_POLL,
    DELETE_POLL,
    ADD_POLL,

    FULL_NOTICE = 140,
    VIEW_NOTICE,
    EDIT_NOTICE,
    DELETE_NOTICE,
    ADD_NOTICE,

    FULL_PROFILE = 150,
    VIEW_PROFILE,
    EDIT_PROFILE,
    DELETE_PROFILE,
    ADD_PROFILE,

    CUSTOMER_MANAGEMENT = 160,
    SUBSCRIPTION_TOOL,
    VIEW_DOWNLOAD_RESULT,
    VIEW_EDIT_PROFILE,
    ADMINISTRATOR,

    FULL_ADMIN = 170,
    VIEW_ADMIN,
    EDIT_ADMIN,
    DELETE_ADMIN,
    ADD_ADMIN,
}